#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t furydragons"

$L "  _____                 ____                                   "
$L " |  ___|   _ _ __ _   _|  _ \ _ __ __ _  __ _  ___  _ __  ___  "
$L " | |_ | | | | '__| | | | | | | '__/ _` |/ _` |/ _ \| '_ \/ __| "
$L " |  _|| |_| | |  | |_| | |_| | | | (_| | (_| | (_) | | | \__ \ "
$L " |_|   \__,_|_|   \__, |____/|_|  \__,_|\__, |\___/|_| |_|___/ "
$L "                  |___/                 |___/                  "
$L "Welcome to Android `getprop ro.build.version.release` / FuryDragons-`getprop ro.furydragons.version`";
